services:
  - type: worker
    name: mitzvah-whatsapp-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mitzvah_whatsapp_bot.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        value: "+14155238886"
